<h1>Productos destacados</h1>
<div class="product">
    <img src="assets/img/camiseta.png" alt="camiseta" />
    <h2>Camiseta azul</h2>
    <p>30.00 EUR</p>
    <a href="#" class="button">Comprar</a>
</div>
<div class="product">
    <img src="assets/img/camiseta.png" alt="camiseta" />
    <h2>Camiseta azul</h2>
    <p>30.00 EUR</p>
    <a href="#" class="button">Comprar</a>
</div>
<div class="product">
    <img src="assets/img/camiseta.png" alt="camiseta" />
    <h2>Camiseta azul</h2>
    <p>30.00 EUR</p>
    <a href="#" class="button">Comprar</a>
</div>
</div>